name: documentation
on:
  release:
    types: [published, edited]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - uses: actions/setup-python@v5
      
      - name: Install dependencies
        run: |
          pip install pkgconfig six numpy sphinx sphinx_rtd_theme myst-parser sphinxfortran-ng charset_normalizer
          
      - name: Sphinx build
        run: |
          sphinx-build doc _build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/
  deploy:
    needs: docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
